//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAssignments.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C# is good")]
        public string COutput {
            get {
                return ((string)(this["COutput"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Suraj is Humble and Great")]
        public string SampleString {
            get {
                return ((string)(this["SampleString"]));
            }
            set {
                this["SampleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^[a-zA-Z0-9 ]*$")]
        public string SpecialCharacters {
            get {
                return ((string)(this["SpecialCharacters"]));
            }
            set {
                this["SpecialCharacters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Invalid Input: {0}")]
        public string ExceptionMessage {
            get {
                return ((string)(this["ExceptionMessage"]));
            }
            set {
                this["ExceptionMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zinco")]
        public string Vehicle1 {
            get {
                return ((string)(this["Vehicle1"]));
            }
            set {
                this["Vehicle1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VW")]
        public string Vehicle2 {
            get {
                return ((string)(this["Vehicle2"]));
            }
            set {
                this["Vehicle2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BMW")]
        public string Vehicle3 {
            get {
                return ((string)(this["Vehicle3"]));
            }
            set {
                this["Vehicle3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ferrari")]
        public string UpdatedVehicle {
            get {
                return ((string)(this["UpdatedVehicle"]));
            }
            set {
                this["UpdatedVehicle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vehicle 1 after update:")]
        public string VehicleAfterUpdateSignature {
            get {
                return ((string)(this["VehicleAfterUpdateSignature"]));
            }
            set {
                this["VehicleAfterUpdateSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Garbage")]
        public string Truck1 {
            get {
                return ((string)(this["Truck1"]));
            }
            set {
                this["Truck1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dump")]
        public string Truck2 {
            get {
                return ((string)(this["Truck2"]));
            }
            set {
                this["Truck2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Carrier")]
        public string Truck3 {
            get {
                return ((string)(this["Truck3"]));
            }
            set {
                this["Truck3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Display Sorted Trucks:")]
        public string DisplayTrucksSignature {
            get {
                return ((string)(this["DisplayTrucksSignature"]));
            }
            set {
                this["DisplayTrucksSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Display Sorted Cars:")]
        public string DisplayCarsSignature {
            get {
                return ((string)(this["DisplayCarsSignature"]));
            }
            set {
                this["DisplayCarsSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Display Sorted Vehicles:")]
        public string DisplayVehiclesSignature {
            get {
                return ((string)(this["DisplayVehiclesSignature"]));
            }
            set {
                this["DisplayVehiclesSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vehicle:")]
        public string VehicleSignature {
            get {
                return ((string)(this["VehicleSignature"]));
            }
            set {
                this["VehicleSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int MaxRandom {
            get {
                return ((int)(this["MaxRandom"]));
            }
            set {
                this["MaxRandom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MinRandom {
            get {
                return ((int)(this["MinRandom"]));
            }
            set {
                this["MinRandom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wrong Choice!")]
        public string DefaultMessage {
            get {
                return ((string)(this["DefaultMessage"]));
            }
            set {
                this["DefaultMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter your name:")]
        public string StudentNameSignature {
            get {
                return ((string)(this["StudentNameSignature"]));
            }
            set {
                this["StudentNameSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter your age:")]
        public string StudentAgeSignature {
            get {
                return ((string)(this["StudentAgeSignature"]));
            }
            set {
                this["StudentAgeSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter your choice 0:ENumber, 1:Name, 2:Age :")]
        public string StudentDetailsSignature {
            get {
                return ((string)(this["StudentDetailsSignature"]));
            }
            set {
                this["StudentDetailsSignature"] = value;
            }
        }
    }
}
